### ISSUE TITLE
amaze fileutilities crash at first start

### ISSUE THREAD

**Issue by C-O-D** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#121]
## Exception
* __App Name:__ Amaze Datei-Tools
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.68
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 9 - 28
* __Device:__ htc_ocndugl
* __Model:__ HTC U11
* __Product:__ ocndugl_00401
* __Device ID:__ fe00a9b19e07f4badfa73807bc60cb8517640e122a8096901c50afaef3405c88
<details><summary><b>Crash log </b></summary>

```
java.lang.NullPointerException: cursor.getString(mediaCo…nIdxValues.commonNameIdx) must not be null
	at q3.g$a.a(CursorUtils.kt:44)
	at q3.g$a.c(CursorUtils.kt:27)
	at f3.x.invokeSuspend(FilesViewModel.kt:14)
	at y8.a.resumeWith(ContinuationImpl.kt:4)
	at ob.f0.run(DispatchedTask.kt:18)
	at tb.g.run(LimitedDispatcher.kt:2)
	at ub.k.run(Tasks.kt:1)
	at ub.a.t(CoroutineScheduler.kt:1)
	at ub.a$a.run(CoroutineScheduler.kt:10)
	Suppressed: pa.g: [j1{Cancelling}@2d1c937, Dispatchers.IO]

```

**Comment by StrongArm88** [comment]
## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.69
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 5.0.1 - 21
* __Device:__ jfltecan
* __Model:__ SGH-I337M
* __Product:__ jfltevl
* __Device ID:__ null
<details><summary><b>Crash log </b></summary>

```
java.lang.IllegalStateException: Circular dependencies cannot exist in RelativeLayout
	at android.widget.RelativeLayout$DependencyGraph.getSortedViews(RelativeLayout.java:1704)
	at android.widget.RelativeLayout.sortChildren(RelativeLayout.java:383)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:390)
	at android.view.View.measure(View.java:18596)
	at androidx.recyclerview.widget.RecyclerView$o.measureChildWithMargins(RecyclerView.java:14)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:11)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:66)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:18596)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
	at android.view.View.measure(View.java:18596)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:5)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:1)
	at android.view.View.measure(View.java:18596)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:18596)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:18596)
	at androidx.constraintlayout.widget.ConstraintLayout$b.b(ConstraintLayout.java:72)
	at u.b.a(BasicMeasure.java:15)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:150)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:15)
	at android.view.View.measure(View.java:18596)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:18596)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:45)
	at android.view.View.measure(View.java:18596)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:18596)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
	at android.view.View.measure(View.java:18596)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2897)
	at android.view.View.measure(View.java:18596)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2248)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1306)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1548)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
> ## Issue explanation (write below this line)
> ## Exception
> * **App Name:** Amaze File Utilities
> * **Package:** com.amaze.fileutilities
> * **Version:** 1.69
> * **User Action:** UI Error
> * **Request:** Application crash
> * **OS:** Linux Android 5.0.1 - 21
> * **Device:** jfltecan
> * **Model:** SGH-I337M
> * **Product:** jfltevl
> * **Device ID:** null
> 
> Crash log

Will publish fix asap thanks for pointing
