### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Shopimisrel** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#134]
## Exception
* __App Name:__ Amaze - כלי עזר לקבצים
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.71
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ a12s
* __Model:__ SM-A127F
* __Product:__ a12snnxx
<details><summary><b>Crash log </b></summary>

```
java.lang.NullPointerException
	at q3.a$a.invoke(AbstractMediaFileInfoOperationsFragment.kt:10)
	at u2.c.onClick(Unknown Source:3)
	at androidx.appcompat.app.AlertController$c.handleMessage(AlertController.java:3)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>
<hr>

**Comment by Shopimisrel** [comment]
## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze - כלי עזר לקבצים
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.74
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ a12s
* __Model:__ SM-A127F
* __Product:__ a12snnxx
* __Device ID:__ null
<details><summary><b>Crash log </b></summary>

```
java.lang.NullPointerException
	at x3.a$b.invoke(AbstractMediaFileInfoOperationsFragment.kt:58)
	at x3.u0.onClick(R8$$SyntheticClass:11)
	at androidx.appcompat.app.AlertController$c.handleMessage(AlertController.java:38)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>
<hr>

**Comment by Shopimisrel** [comment]
## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze - כלי עזר לקבצים
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.74
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ a12s
* __Model:__ SM-A127F
* __Product:__ a12snnxx
* __Device ID:__ null
<details><summary><b>Crash log </b></summary>

```
java.lang.IllegalArgumentException: saveBackStack("ce5a9d33-40f2-4689-abf5-1fd9877f9ab0") included FragmentTransactions must use setReorderingAllowed(true) to ensure that the back stack can be restored as an atomic operation. Found BackStackEntry{72b977f #1} that did not use setReorderingAllowed(true).
	at androidx.fragment.app.g0$p.a(FragmentManager.java:75)
	at androidx.fragment.app.g0.z(FragmentManager.java:43)
	at androidx.fragment.app.g0$f.run(FragmentManager.java:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>
<hr>
