### ISSUE TITLE
Amaze just crashed randomly as I was editing a photo

### ISSUE THREAD

**Issue by Juggalo303** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#167]
## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.76
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ U616AT
* __Model:__ U616AT
* __Product:__ U616AT
* __Device ID:__ f1c9df8acdce172258271b0dcc89091204da9f722ad7cac2a3d16356872aff5b
<details><summary><b>Crash log </b></summary>

```
java.lang.RuntimeException: glAttachShader: glError 1285
	at d.a.a(Unknown Source:30)
	at z8.j.onDrawFrame(ImageFilterView.kt:64)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1581)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1280)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Thanks, will look at the issue.
