### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by git-devanand** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#185]
## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.76
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux motorola/hanoip_retail/hanoip:12/S2RI32.32-20-7/7dcd6-70dcd:user/release-keys 12 - 31
* __Device:__ hanoip
* __Model:__ moto g(40) fusion
* __Product:__ hanoip_retail
* __Device ID:__ 4f44e98ebcc585409c82f52d0ffe63e888f79f66fe5489135f05c7308cb3a3cc
<details><summary><b>Crash log </b></summary>

```
java.lang.IllegalStateException: Fragment TransferFragment{c3bcba8} (6da3f4ed-3a44-4e60-89ee-91b54f960bf6) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:18)
	at com.amaze.fileutilities.home_page.ui.transfer.TransferFragment.w(TransferFragment.kt:8)
	at com.amaze.fileutilities.home_page.ui.transfer.TransferFragment$b.onFinish(TransferFragment.kt:34)
	at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:142)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

```
</details>
<hr>

**Comment by git-devanand** [comment]
UI Error

**Comment by CATBEEF1** [comment]
## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.77
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ a23xq
* __Model:__ SM-A236U
* __Product:__ a23xqsq
* __Device ID:__ 595ed0f01361fa102069f5dc26590c0b0fb981336f795146be39af3578fe1156
<details><summary><b>Crash log </b></summary>

```
java.lang.NullPointerException
	at x3.a$b.invoke(AbstractMediaFileInfoOperationsFragment.kt:58)
	at b3.g.onClick(R8$$SyntheticClass:73)
	at androidx.appcompat.app.AlertController$c.handleMessage(AlertController.java:38)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
> 

How did you get this crash?

**Comment by CATBEEF1** [comment]
> > 
> 
> How did you get this crash?

I don't quite remember tho but I ran it 2 more times and it worked
