### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#25]
## Exception
* App Name: Amaze File Utilities
* Package: com.amaze.fileutilities
* Version: 1.29
* User Action: UI Error
* Request: Application crash
* OS: Linux Android 8.1.0 - 27
* Device: TB-8704X
* Model: Lenovo TB-8704X
* Product: TB-8704X
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArithmeticException: divide by zero
 at com.amaze.fileutilities.home_page.ui.files.FilesViewModel$internalStorageStats$1.invokeSuspend(FilesViewModel.kt:72)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

</details>
<hr>

**Comment by VishalNehra** [comment]
fixed
