### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#26]
```
## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.29
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 8.1.0 - 27
* __Device:__ TB-8704X
* __Model:__ Lenovo TB-8704X
* __Product:__ TB-8704X
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1771)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6518)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
</details>
<hr>
```

**Comment by VishalNehra** [comment]
@shuvashish76 how did you get this crash?
