### ISSUE TITLE
Initial storage access crash

### ISSUE THREAD

**Issue by shuvashish76** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#3]
## Issue explanation (write below this line)
App crashed before showing the welcome screen...

## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.14
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 8.1.0 - 27
* __Device:__ TB-8704X
* __Model:__ Lenovo TB-8704X
* __Product:__ TB-8704X
<details><summary><b>Crash log </b></summary><p>

```
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file from pid=28069, uid=10105 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:2013)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
	at android.content.ContentResolver.query(ContentResolver.java:756)
	at android.content.ContentResolver.query(ContentResolver.java:705)
	at android.content.ContentResolver.query(ContentResolver.java:663)
	at com.amaze.fileutilities.utilis.CursorUtils$Companion.getMediaFilesCount(CursorUtils.kt:106)
	at com.amaze.fileutilities.home_page.ui.files.FilesViewModel$internalStorageStats$1.invokeSuspend(FilesViewModel.kt:66)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
fixed in 1.16+
