### ISSUE TITLE
Amaze utilities

### ISSUE THREAD

**Issue by dp35654** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#375]
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager.debug
* __Version:__ 3.10
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ berlna
* __Model:__ motorola edge (2021)
* __Product:__ berlna_global
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment MainFragment{257b286} (a0450b57-2c03-46d4-90cf-65251b59f340) is not currently in the FragmentManager
	at androidx.fragment.app.FragmentManager.putFragment(FragmentManager.java:1013)
	at com.amaze.filemanager.ui.fragments.TabFragment.onSaveInstanceState(TabFragment.java:249)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3288)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:681)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:647)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2382)
	at androidx.fragment.app.FragmentManager.lambda$attachController$4$androidx-fragment-app-FragmentManager(FragmentManager.java:2660)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda4.saveState(Unknown Source:2)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:383)
	at com.amaze.filemanager.ui.activities.MainActivity.onSaveInstanceState(MainActivity.java:1325)
	at android.app.Activity.performSaveInstanceState(Activity.java:2266)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1565)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5924)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5309)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5275)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5340)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2399)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8094)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)

```
</details>
<hr>

**Comment by dp35654** [comment]
I have no idea what's going on? It said share, so hopefully you guys know what is going on

**Comment by Devsblacksin** [comment]
## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ v1.92
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux samsung/a25xsq/a25x:14/UP1A.231005.007/A256USQU1AWL3:user/release-keys 14 - 34
* __Device:__ a25x
* __Model:__ SM-A256U
* __Product:__ a25xsq
* __Device ID:__ 032a216a615180826560d2c078eff9eab315d2dbfbd3a9da9a9dccd6f571cf3a
<details><summary><b>Crash log </b></summary>

```
java.lang.RuntimeException: Could not compile and link shader!
	at android.filterfw.core.ShaderProgram.<init>(ShaderProgram.java:55)
	at android.filterpacks.imageproc.LomoishFilter.initProgram(LomoishFilter.java:139)
	at android.filterpacks.imageproc.LomoishFilter.process(LomoishFilter.java:183)
	at android.filterfw.core.Filter.performProcess(Filter.java:471)
	at android.filterfw.core.FilterFunction.execute(FilterFunction.java:80)
	at android.filterfw.core.FilterFunction.executeWithArgList(FilterFunction.java:97)
	at android.media.effect.SingleFilterEffect.apply(SingleFilterEffect.java:87)
	at n8.j.onDrawFrame(ImageFilterView.kt:798)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1584)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1283)

```
</details>
<hr>

**Comment by dp35654** [comment]
Even though I paid for a lifetime subscription, I uninstalled it! To much
trouble, Thanks Debbie
