### ISSUE TITLE
Canvas Error first time Analyzing storage

### ISSUE THREAD

**Issue by timhorn1** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#45]
## Issue explanation (write below this line)
Error with showing bitmap preview of duplicate images. After three times of trying it worked with out an error, but doesn't  load anymore images.

## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.42
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ gts7l
* __Model:__ SM-T875
* __Product:__ gts7leea
* __Device ID:__ d497caf9ea90f6ca3af8754778de4bae8d1236301087735af8260e036317e912
<details><summary><b>Crash log </b></summary>

```
java.lang.RuntimeException: Canvas: trying to draw too large(1510042500bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:97)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:560)
	at android.widget.ImageView.onDraw(ImageView.java:1462)
	at com.google.android.material.imageview.ShapeableImageView.onDraw(ShapeableImageView.java:1)
	at android.view.View.draw(View.java:23898)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.draw(View.java:23901)
	at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:2238)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.draw(View.java:23901)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.draw(View.java:23901)
	at android.widget.ScrollView.draw(ScrollView.java:2846)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:5)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:4)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:4)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:5)
	at android.view.View.draw(View.java:23901)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.draw(View.java:23901)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1378)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5432)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5140)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4204)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2911)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10458)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
fixed with #1.43
