### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by suryaanshah** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#58]
## Issue explanation (write below this line)
Failure opening a .docx file

## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.33
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 7.0 - 24
* __Device:__ TB-7504X
* __Model:__ Lenovo TB-7504X
* __Product:__ LenovoTB-7504X
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
	at org.zwobble.mammoth.internal.util.Base64Encoding.streamToBase64(Base64Encoding.java:17)
	at org.zwobble.mammoth.internal.util.Base64Encoding.streamToBase64(Base64Encoding.java:12)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtmlOptions.lambda$static$0(DocumentToHtmlOptions.java:20)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtmlOptions$$ExternalSyntheticLambda0.convert(Unknown Source)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor.lambda$visit$12$org-zwobble-mammoth-internal-conversion-DocumentToHtml$ElementConverterVisitor(DocumentToHtml.java:341)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor$$ExternalSyntheticLambda6.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:210)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor.visit(DocumentToHtml.java:339)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor.visit(DocumentToHtml.java:146)
	at org.zwobble.mammoth.internal.documents.Image.accept(Image.java:35)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertToHtml(DocumentToHtml.java:369)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.lambda$convertToHtml$3$org-zwobble-mammoth-internal-conversion-DocumentToHtml(DocumentToHtml.java:138)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$$ExternalSyntheticLambda1.apply(Unknown Source)
	at org.zwobble.mammoth.internal.util.Lists.lambda$eagerFlatMap$0(Lists.java:65)
	at org.zwobble.mammoth.internal.util.Lists$$ExternalSyntheticLambda1.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:268)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1361)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:235)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:500)
	at org.zwobble.mammoth.internal.util.Lists.eagerFlatMap(Lists.java:66)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertToHtml(DocumentToHtml.java:136)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertChildrenToHtml(DocumentToHtml.java:143)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.access$400(DocumentToHtml.java:25)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor.lambda$visit$2$org-zwobble-mammoth-internal-conversion-DocumentToHtml$ElementConverterVisitor(DocumentToHtml.java:165)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor$$ExternalSyntheticLambda1.get(Unknown Source)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor.visit(DocumentToHtml.java:197)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor.visit(DocumentToHtml.java:146)
	at org.zwobble.mammoth.internal.documents.Run.accept(Run.java:77)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertToHtml(DocumentToHtml.java:369)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.lambda$convertToHtml$3$org-zwobble-mammoth-internal-conversion-DocumentToHtml(DocumentToHtml.java:138)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$$ExternalSyntheticLambda1.apply(Unknown Source)
	at org.zwobble.mammoth.internal.util.Lists.lambda$eagerFlatMap$0(Lists.java:65)
	at org.zwobble.mammoth.internal.util.Lists$$ExternalSyntheticLambda1.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:268)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1361)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:235)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:500)
	at org.zwobble.mammoth.internal.util.Lists.eagerFlatMap(Lists.java:66)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertToHtml(DocumentToHtml.java:136)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertChildrenToHtml(DocumentToHtml.java:143)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.access$400(DocumentToHtml.java:25)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor.lambda$visit$0$org-zwobble-mammoth-internal-conversion-DocumentToHtml$ElementConverterVisitor(DocumentToHtml.java:150)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor$$ExternalSyntheticLambda12.get(Unknown Source)
	at org.zwobble.mammoth.internal.styles.HtmlPathElement.lambda$wrap$0$org-zwobble-mammoth-internal-styles-HtmlPathElement(HtmlPathElement.java:20)
	at org.zwobble.mammoth.internal.styles.HtmlPathElement$$ExternalSyntheticLambda0.get(Unknown Source)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor.visit(DocumentToHtml.java:160)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$ElementConverterVisitor.visit(DocumentToHtml.java:146)
	at org.zwobble.mammoth.internal.documents.Paragraph.accept(Paragraph.java:42)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertToHtml(DocumentToHtml.java:369)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.lambda$convertToHtml$3$org-zwobble-mammoth-internal-conversion-DocumentToHtml(DocumentToHtml.java:138)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml$$ExternalSyntheticLambda1.apply(Unknown Source)
	at org.zwobble.mammoth.internal.util.Lists.lambda$eagerFlatMap$0(Lists.java:65)
	at org.zwobble.mammoth.internal.util.Lists$$ExternalSyntheticLambda1.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:268)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1361)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:235)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:500)
	at org.zwobble.mammoth.internal.util.Lists.eagerFlatMap(Lists.java:66)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertToHtml(DocumentToHtml.java:136)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertChildrenToHtml(DocumentToHtml.java:143)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertToHtml(DocumentToHtml.java:89)
	at org.zwobble.mammoth.internal.conversion.DocumentToHtml.convertToHtml(DocumentToHtml.java:29)
	at org.zwobble.mammoth.internal.InternalDocumentConverter.lambda$convertToHtml$4(InternalDocumentConverter.java:56)
	at org.zwobble.mammoth.internal.InternalDocumentConverter$$ExternalSyntheticLambda17.apply(Unknown Source)
	at org.zwobble.mammoth.internal.results.InternalResult.flatMap(InternalResult.java:76)
	at org.zwobble.mammoth.internal.InternalDocumentConverter.convertToHtml(InternalDocumentConverter.java:56)
	at org.zwobble.mammoth.internal.InternalDocumentConverter.lambda$convertToHtml$0$org-zwobble-mammoth-internal-InternalDocumentConverter(InternalDocumentConverter.java:42)
	at org.zwobble.mammoth.internal.InternalDocumentConverter$$ExternalSyntheticLambda11.apply(Unknown Source)
	at org.zwobble.mammoth.internal.InternalDocumentConverter.withDocxFile(InternalDocumentConverter.java:91)
	at org.zwobble.mammoth.internal.InternalDocumentConverter.lambda$convertToHtml$1$org-zwobble-mammoth-internal-InternalDocumentConverter(InternalDocumentConverter.java:41)
	at org.zwobble.mammoth.internal.InternalDocumentConverter$$ExternalSyntheticLambda10.get(Unknown Source)
	at org.zwobble.mammoth.internal.util.PassThroughException.unwrap(PassThroughException.java:16)
	at org.zwobble.mammoth.internal.InternalDocumentConverter.convertToHtml(InternalDocumentConverter.java:40)
	at org.zwobble.mammoth.DocumentConverter.convertToHtml(DocumentConverter.java:77)
	at com.amaze.fileutilities.docx_viewer.DocxViewerActivity.onCreate(DocxViewerActivity.kt:55)
	at android.app.Activity.performCreate(Activity.java:6675)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[zip file "/data/app/com.amaze.fileutilities-1/base.apk", zip file "/data/app/com.amaze.fileutilities-1/split_config.arm64_v8a.apk", zip file "/data/app/com.amaze.fileutilities-1/split_config.en.apk", zip file "/data/app/com.amaze.fileutilities-1/split_config.hdpi.apk"],nativeLibraryDirectories=[/data/app/com.amaze.fileutilities-1/lib/arm64, /data/app/com.amaze.fileutilities-1/base.apk!/lib/arm64-v8a, /data/app/com.amaze.fileutilities-1/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.amaze.fileutilities-1/split_config.en.apk!/lib/arm64-v8a, /data/app/com.amaze.fileutilities-1/split_config.hdpi.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 96 more
	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.amaze.fileutilities-1/split_config.arm64_v8a.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:373)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:78)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
		at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
		at dalvik.system.DexPathList.<init>(DexPathList.java:126)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:525)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:558)
		at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1921)
		at android.app.LoadedApk.getResources(LoadedApk.java:771)
		at android.app.ContextImpl.<init>(ContextImpl.java:2055)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2000)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5394)
		at android.app.ActivityThread.-wrap2(ActivityThread.java)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
		... 6 more
	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.amaze.fileutilities-1/split_config.en.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:373)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:78)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
		at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
		at dalvik.system.DexPathList.<init>(DexPathList.java:126)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:525)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:558)
		at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1921)
		at android.app.LoadedApk.getResources(LoadedApk.java:771)
		at android.app.ContextImpl.<init>(ContextImpl.java:2055)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2000)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5394)
		at android.app.ActivityThread.-wrap2(ActivityThread.java)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
		... 6 more
	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.amaze.fileutilities-1/split_config.hdpi.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:373)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:78)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
		at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
		at dalvik.system.DexPathList.<init>(DexPathList.java:126)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:525)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:558)
		at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1921)
		at android.app.LoadedApk.getResources(LoadedApk.java:771)
		at android.app.ContextImpl.<init>(ContextImpl.java:2055)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2000)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5394)
		at android.app.ActivityThread.-wrap2(ActivityThread.java)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
		... 6 more

```
</details>
<hr>

**Comment by MbappeTNul** [comment]
## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.50
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 7.0 - 24
* __Device:__ h1
* __Model:__ LG-H850
* __Product:__ h1_global_com
* __Device ID:__ caf1d5607e8ea6c7bd52e8a3d79067641c30ec89a5c1da246b574f01d9c1aaf4
<details><summary><b>Crash log </b></summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 2560012 byte allocation with 2448584 free bytes and 2MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeFileDescriptor(Native Method)
	at android.graphics.BitmapFactory.decodeFileDescriptor(BitmapFactory.java:683)
	at android.graphics.BitmapFactory.decodeFileDescriptor(BitmapFactory.java:715)
	at q2.k.a(AudioUtils.kt:3)
	at h3.e.c(CursorUtils.kt:24)
	at h3.e.a(CursorUtils.kt:27)
	at a3.r.invokeSuspend(FilesViewModel.kt:22)
	at m8.a.resumeWith(ContinuationImpl.kt:4)
	at cb.d0.run(DispatchedTask.kt:18)
	at ib.a.B(CoroutineScheduler.kt:1)
	at ib.a$a.run(CoroutineScheduler.kt:10)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Fixed with v1.52
