### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by WhenControllersFly** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#68]
## Issue explanation (write below this line)

open app, grant permissions, 2 seconds later, app crash

## Exception
* __App Name:__ Amaze File Utilities
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.51
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ oriole
* __Model:__ Pixel 6
* __Product:__ oriole
* __Device ID:__ 3885141a37735c48b8e5cf14658a8dbc3cf0ef5ea4a5997efc3c59190537e817
<details><summary><b>Crash log </b></summary>

```
CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.3) /home/quickbirdstudios/opencv/releases/opencv-4.5.3/modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
]
	at org.opencv.imgproc.Imgproc.resize_0(Native Method)
	at org.opencv.imgproc.Imgproc.resize(Imgproc.java:1)
	at h3.n$a.g(ImgUtils.kt:4)
	at a3.o.invokeSuspend(FilesViewModel.kt:28)
	at m8.a.resumeWith(ContinuationImpl.kt:4)
	at cb.d0.run(DispatchedTask.kt:18)
	at ib.a.B(CoroutineScheduler.kt:1)
	at ib.a$a.run(CoroutineScheduler.kt:10)

```
</details>
<hr>

**Comment by VishalNehra** [comment]
Fixed with v1.52
