### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Shopimisrel** [TeamAmaze/AmazeFileUtilities-Issue-Tracker#92]
## Exception
* __App Name:__ Amaze - כלי עזר לקבצים
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.61
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Blackview/A80Plus/A80Plus/release-keys 10 - 29
* __Device:__ A80Plus
* __Model:__ A80Plus
* __Product:__ A80Plus
<details><summary><b>Crash log </b></summary>

```
java.lang.IllegalStateException: Couldn't read row 6509, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:469)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
	at q3.g$a.a(CursorUtils.kt:10)
	at f3.s.invokeSuspend(FilesViewModel.kt:12)
	at y8.a.resumeWith(ContinuationImpl.kt:4)
	at ob.f0.run(DispatchedTask.kt:18)
	at tb.g.run(LimitedDispatcher.kt:2)
	at ub.k.run(Tasks.kt:1)
	at ub.a.t(CoroutineScheduler.kt:1)
	at ub.a$a.run(CoroutineScheduler.kt:10)
	Suppressed: pa.g: [j1{Cancelling}@7002089, Dispatchers.IO]

```
</details>
<hr>

**Comment by Shopimisrel** [comment]
## Issue explanation (write below this line)



## Exception
* __App Name:__ Amaze - כלי עזר לקבצים
* __Package:__ com.amaze.fileutilities
* __Version:__ 1.61
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Blackview/A80Plus/A80Plus:10/QP1A.190711.020/release-keys 10 - 29
* __Device:__ A80Plus
* __Model:__ A80Plus
* __Product:__ A80Plus
* __Device ID:__ 59c906887974c4e979b46038a212b954228b521c277e44be3871c601b2e5b04b
<details><summary><b>Crash log </b></summary>

```
java.lang.IllegalStateException: Couldn't read row 6508, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:469)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
	at q3.g$a.a(CursorUtils.kt:10)
	at f3.i$d.invokeSuspend(FilesViewModel.kt:5)
	at y8.a.resumeWith(ContinuationImpl.kt:4)
	at ob.f0.run(DispatchedTask.kt:18)
	at tb.g.run(LimitedDispatcher.kt:2)
	at ub.k.run(Tasks.kt:1)
	at ub.a.t(CoroutineScheduler.kt:1)
	at ub.a$a.run(CoroutineScheduler.kt:10)
	Suppressed: pa.g: [j1{Cancelling}@f089038, Dispatchers.IO]

```
</details>
<hr>
